# Generated by Django 3.2.8 on 2024-08-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
